{
    'name': 'TCF Studio Migration19',
    'version': '19.0.1.3.41',
    'summary': 'Migrates Odoo Studio custom x_ fields to native Python fields',
    'author': 'Al Jawad',
    'category': 'Technical',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'sale_management',
        'stock',
        'mrp',
        'mrp_picking',
        'link_mrp_sale',
        'account',
        'product',
        'fixed_uom_sale',
    ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/product_template_server_actions.xml',
        'data/perfume_server_actions.xml',
        'views/brand_tag_views.xml',
        'views/brand_brand_views.xml',
        'views/fragrance_uses_views.xml',
        'views/perfume_perfume_views.xml',
        'views/product_purpose_category_views.xml',
        'views/product_purpose_views.xml',
        'views/product_template_views.xml',
        'views/sale_order_views.xml',
        'views/stock_picking_views.xml',
        'views/stock_move_line_views.xml',
        'views/mrp_production_views.xml',
        'views/menu.xml',
        'views/report_layout_boxed.xml',
        'views/report_picking_v16.xml',
        'views/report_deliveryslip_v16.xml',
        'views/report_mo_cost_analysis.xml',
        'data/report_layout_parity.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': False,
    'auto_install': False,
}
