from . import brand_tag
from . import brand_brand
from . import fragrance_uses
from . import product_purpose_category
from . import product_purpose
from . import perfume_perfume
from . import product_template
from . import product_product
from . import sale_order
from . import res_partner_bank
from . import res_company
from . import report_studio_fixes
from . import stock_picking
from . import stock_move_line
from . import stock_move
from . import sale_order_line
from . import stock_quant
from . import mrp_production
from . import report_mo_cost_analysis
